### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by AryToNeX** [PurePlugins/PureChat#11]
Please can you add {faction_name} tag and {faction_rank} tag for displaying only faction name or faction rank and allowing entire faction tags personalization?

If you can add this servers' chat can be like this:
```
PlayerA: Hello <-- player without faction
[Leader->Infinity] PlayerB: Hi! <-- player with faction (leader)
[Officer->Infinity] PlayerC: How are you! <-- officer
[Infinity] PlayerD: Fine, thanks! <-- member
```

For now we can realize things like:
```
[...] PlayerA: Hello
[**Infinity] PlayerB: Hi!
[*Infinity] PlayerC: How are you?
[*Infinity] PlayerD: Fine, thanks!
```

**Comment by AryToNeX** [comment]
Another feature request: Can you add custom prefixes for players and commands like /setprefix <player> <prefix-id>?

For example Pro, YouTuber, etc.

And customizations like this
```
# {prefixes} tag shows all prefixes obtained by the player, {prefix-id} shows only a definite custom prefix obtained by the player
# if no prefixes (or custom prefix) are obtained, then use no-prefix-achieved as fallback
custom-prefixes: # list of prefixes
  # prefix-id: Showed Prefix
  youtuber: YouTuber
  pro: Pro
custom-prefixes-separator: " - " # if multiple prefixes are showed using {prefixes} tag, this separate them
custom-prefixes-quotes: " [{p}]" # if we would make things like [Pro], [YouTuber], [Pro - YouTuber] and we want to keep clean normal players
no-prefix-achieved: # message when a custom prefix isn't obtained by the player
  show: true # if false {prefixes} and {prefix-id} tags are blank
  message: "No Prefix"

[...]

Guest:
  default-chat: "[Guest]{prefixes} {display_name} > {message}"
  OR
  default-chat: "[Guest]{pro}{youtuber} {display_name} > {message}"
```

Then, in chat:
```
[Guest] PlayerA: Hello!
[Guest] [YouTuber] PlayerB: Hi! You all are in my video!
[Guest] [Pro] PlayerC: Yeah! Let's do parkour!
[Guest] [Pro - YouTuber] PlayerD: Yeeah! Today I beat you!

and so on...
```

Okay, maybe it's so complicated, but it would be awesome!
